### ISSUE TITLE
talent2优化项

### ISSUE THREAD

**Issue by Kaviilee** [JX3BOX/jx3box-talent2#2]
一些关于镇派的后续优化

**Comment by Kaviilee** [comment]
### 遮罩层优化
目前使用的是 `before` 的方式，判断非常复杂且难以管理。作为后续优化点

-------------------------
- [x] 完成

**Comment by iRuxu** [comment]
> 云裳 翔天镇派，第三层描述错误，与1、2层不一样

用户反馈如上，可能需要查一下Buff/skill表，确定是哪个问题

**Comment by Kaviilee** [comment]
## 易筋经心法 心棍满层显示错误
显示成了苦厄的满层效果
