### ISSUE TITLE
支持丐帮

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-talent2#9]
可以增加一种single模式。
![31937dffbcc54fb33710257fc8228af9](https://github.com/JX3BOX/jx3box-talent2/assets/8476969/9412c5f3-d626-426b-9442-a2ec9fc11e4b)
![7d42cced1e3556f6eee4acfd27793de7_720](https://github.com/JX3BOX/jx3box-talent2/assets/8476969/97d00059-aa3f-4c75-a736-9cfbb97f7812)

**Comment by M-ls** [comment]
体服镇派改动：


丐帮：
talenttab表现为[1]为左镇派[2]为右镇派[3]为丐帮镇派，开发是否需要src/talent2.json配合改动？对应源文件
![image](https://github.com/JX3BOX/jx3box-talent2/assets/36070993/ba2adfc3-bd06-4c51-ae16-127212a64002)


每行解锁条件为 5 10 10 15 20 其中3 5行互斥


非丐帮：
7行4列，其中一行互斥（一般为6，7行），实际表现及源文件
![image](https://github.com/JX3BOX/jx3box-talent2/assets/36070993/a4fd5fd3-65ed-4353-b59c-b325dc23f601)
![image](https://github.com/JX3BOX/jx3box-talent2/assets/36070993/8faadfc4-28c6-4082-91e1-6b7fafa371e1)


每行解锁条件为5 10 15 20 25 25 29（第二心法）


部分节点有特殊前置，实际表现及对应源文件
![image](https://github.com/JX3BOX/jx3box-talent2/assets/36070993/3773099b-7f6e-4a24-860f-2c52282b0268)
![image](https://github.com/JX3BOX/jx3box-talent2/assets/36070993/80b0a90a-d100-46ea-bb1b-a5b8b6109175)

**Comment by M-ls** [comment]
补：丐帮互斥是3个
![image](https://github.com/JX3BOX/jx3box-talent2/assets/36070993/ab9bcb41-535c-4fca-93d6-4ab23107036e)

**Comment by Kaviilee** [comment]
需要在talent2.json中新增mutex和condition字段，分别用于记录互斥条件和激活条件

**Comment by M-ls** [comment]
![image](https://github.com/JX3BOX/jx3box-talent2/assets/36070993/d29d08b8-ccc1-4f76-a885-7fc9e3bdb179)
互斥节点测试通过 注意此项改动依赖npm版本 修改后需要version+1 前端库线上部署才能同步
（注：output中文件改动不需要更新npm版本）
